### ISSUE TITLE
Android 8.1 not working

### ISSUE THREAD

**Issue by tremblerz** [Path-Check/covid-safe-paths#113]

**Comment by harshvitra** [comment]
Hey, I just checked it works in Android 8.1

Was the issue for a specific device ?

**Comment by rparet** [comment]
@tremblerz some more context here? perhaps this is now working again or is device specific?

**Comment by tstirrat** [comment]
Closing, not able to reproduce on a 8.1 emulator. Reopen with device specifics if you can reproduce.
