### ISSUE TITLE
Add community section for people to engage in conversation

### ISSUE THREAD

**Issue by code247** [Path-Check/covid-safe-paths#157]
Add section where infected people can publicly/anonymously share their stories describing onset, treatment, recovery, difficulties faced.

**Comment by heri** [comment]
What about a feature like Waze where people can mark zones that are infected (for example, they've seen an ambulance taking away an infected person from their building. or the county released new numbers about new local infections with their location)

**Comment by denispapakul** [comment]
@code247 I can do it, actually need to know, how it should be work.

**Comment by Patrick-Erichsen** [comment]
Closing this issue out as we have taken it into consideration and documented the feedback on [this page in Jira](https://pathcheck.atlassian.net/wiki/spaces/SAFE/pages/81265028/GitHub+Issues+-+Community+Feature+Requests).
