### ISSUE TITLE
Crash Report on Android: Context.startForegroundService

### ISSUE THREAD

**Issue by vitorpamplona** [Path-Check/covid-safe-paths#181]
Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{41ba6b u0 edu.mit.privatekit/com.marianhello.bgloc.service.LocationServiceImpl}

Affecting version 0.5.4 (March 21) and 0.5.6 (March 23) 

Phone | Count | % 
------------ | ------------- | -----------
Pixel 2 XL (taimen) | 5	| 8.3%
Galaxy Note9 (crownqltesq) |  4	| 6.7%
Mi A2 (jasmine_sprout)	| 4	| 6.7%
Galaxy S9+ (star2qltechn) |  3	| 5.0%
Galaxy S10 (beyond1q)	| 3	| 5.0%
Mi A3 (laurel_sprout)| 	3	| 5.0%
Galaxy M30s (m30s)	| 2	| 3.3%
Pixel 4 (flame)	| 2	| 3.3%
Galaxy Note10+ (d2s)| 2	| 3.3%
Pixel 2 (walleye)	| 2	| 3.3%
LG V35 ThinQ (judyp)	| 2	| 3.3%
Galaxy S8 (dreamlte)	| 2	| 3.3%
Pixel XL (marlin)	| 2	| 3.3%
Galaxy S10e (beyond0q)	| 2	| 3.3%
Galaxy S9 (starqltesq)	| 2	| 3.3%
Pixel 3 XL (crosshatch)	| 2	| 3.3%
Galaxy S10 (beyond1)	| 1	1| .7%
Pixel (sailfish)	|  1	| 1.7%
Galaxy S8+ (dream2qltesq)	| 1	| 1.7%
PH-1 (mata)	| 1	| 1.7%
Others	| 14	| 23.3%

OS | Count | %
------------ | ------------- | -----------
Android 10 | 43 | 71.7%
Android 9 | 17 | 28.3%

Stack: 
```
"main" tid=1 Native
"main" prio=5 tid=1 Native
  | group="main" sCount=1 dsCount=0 flags=1 obj=0x7600c018 self=0x6f64414c00
  | sysTid=14993 nice=0 cgrp=default sched=0/0 handle=0x6feae1b560
  | state=S schedstat=( 212359040 104182423 200 ) utm=8 stm=12 core=0 HZ=100
  | stack=0x7fcacb4000-0x7fcacb6000 stackSize=8MB
  | held mutexes=
  #00  pc 00000000000712a8  /system/lib64/libc.so (__epoll_pwait+8)
  #01  pc 00000000000141c0  /system/lib64/libutils.so (android::Looper::pollInner(int)+144)
  #02  pc 000000000001408c  /system/lib64/libutils.so (android::Looper::pollOnce(int, int*, int*, void**)+60)
  #03  pc 000000000012c294  /system/lib64/libandroid_runtime.so (android::android_os_MessageQueue_nativePollOnce(_JNIEnv*, _jobject*, long, int)+44)
  at android.os.MessageQueue.nativePollOnce (Native method)
  at android.os.MessageQueue.next (MessageQueue.java:326)
  at android.os.Looper.loop (Looper.java:181)
  at android.app.ActivityThread.main (ActivityThread.java:7073)
  at java.lang.reflect.Method.invoke (Native method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:494)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:965)
```

**Comment by shubendrak** [comment]
I can look into this ticket. Request the moderator to assign this ticket to me.

**Comment by shubendrak** [comment]
@vitorpamplona i am unable to simulate this crash. Can you provide more info how to simulate this crash.

**Comment by Patrick-Erichsen** [comment]
Closing this as we have work in-flight to patch our geolocation library with a fix for this issue.
