### ISSUE TITLE
FEATURE: Add Face/Pin/whatever unlock on open

### ISSUE THREAD

**Issue by penrods** [Path-Check/covid-safe-paths#19]
Use the operating system's current unlocking mechanism to open the app and show the data. The idea is to minimize snooping without the permission of the phone's owner. A good example of good implementation is the unlocking feature of Signal's Messaging app. 

Implementations have to work on iOS and Android.

**Comment by nic-rodriguez** [comment]
Plan is to use Face/TouchID if available, then default to pin if not available or too many failures.

**Comment by penrods** [comment]
This is being implemented in #118

**Comment by harshvitra** [comment]
> This is being implemented in #118

#118  is closed, we need someone to rework on this maybe

@penrods what would be priority for this one ?
