### ISSUE TITLE
Allow Backups

### ISSUE THREAD

**Issue by WriteCodeEveryday** [Path-Check/covid-safe-paths#195]
I understand there's security concerns, but if we're moving from phone to phone... it would be nice to take a copy of the GPS data with us... you can use a custom BackupProvider that requires a password (show it on the app if needed)

**Comment by greggles** [comment]
I can think of a bit of a workaround for this:

1. Click the export button.
2. Click Share.
3. Push the file somewhere you have access to via email or whatever other options are available.

Depending on how you hope to use the file that might be enough, but it's not a full solution for the scenario of importing your history and using your history to check for interactions with locations of known positive cases.

This doesn't really solve importing the data on the new device, but I wanted to share the idea as a short-term workaround.

**Comment by WriteCodeEveryday** [comment]
Yeah, no, that worked perfectly, and you can reimport it to PrivateKit but it does not allow you to take your data on the go.

**Comment by penrods** [comment]
Brainstorming .. would a "Backup" entry under the kebab menu make sense?  Then if you open the app and it sees whatever the backup file is called it could show a Restore and optionally have the Restore sequence delete the backup file.

Does that make sense?

**Comment by WriteCodeEveryday** [comment]
Unfortunately, the backup.ab file is a tar file with some funky stuff that Android will generate.

**Comment by penrods** [comment]
I mean we generate our own file, like PrivateKit_Backup.json or something similar at a standard location.

**Comment by Patrick-Erichsen** [comment]
Closing this issue out as we have taken it into consideration and documented the feedback on [this page in Jira](https://pathcheck.atlassian.net/wiki/spaces/SAFE/pages/81265028/GitHub+Issues+-+Community+Feature+Requests).
