### ISSUE TITLE
Stopping and starting my location logging didn't work without reboot

### ISSUE THREAD

**Issue by ssirag** [Path-Check/covid-safe-paths#228]
I'm on Android 9, LG V30.

I tested stopping location logging and starting it again, and compared the exports.

In the screenshot below, the first dataset was exported at 3:38 PM EST, the 2nd at 4:15 PM EST, and the 3rd at 5:12 PM EST.  The first and second datasets were identical (I just clicked stop and then start again), while the 3rd was following a reboot before restarting the logging.

After I saw the 2nd dataset was identical to the first, I checked my phone settings, and location was still on.

![image](https://user-images.githubusercontent.com/8559431/77698436-fda57000-6f86-11ea-9103-7a629188b0c6.png)

**Comment by Patrick-Erichsen** [comment]
Closing this issue as we have work in-flight to address location logging issues on reboot.
