### ISSUE TITLE
Location scrubbing on client app side prior to upload

### ISSUE THREAD

**Issue by itamblyn** [Path-Check/covid-safe-paths#252]
In the current design, my understanding is that the user will transmit their full trajectory to the healthcare provider without modification. That healthcare worker will then clean and remove personalized data.

It would be useful if prior to upload, the user has the ability to remove elements of history prior to transmission to the healthcare worker. This will enhance privacy, and decrease the load on the healthcare worker before incorporating the trajectory into the infected user database.

**Comment by rparet** [comment]
Thanks! Client-side redacting is on our list!

**Comment by Patrick-Erichsen** [comment]
Closing this issue out as we have taken it into consideration and documented the feedback on [this page in Jira](https://pathcheck.atlassian.net/wiki/spaces/SAFE/pages/81265028/GitHub+Issues+-+Community+Feature+Requests).
