### ISSUE TITLE
FEATURE: Cache for News view(s)

### ISSUE THREAD

**Issue by penrods** [Path-Check/covid-safe-paths#262]
Background:  The News view of today shows a webpage with information about the application.   Very soon it will also be showing News from the local healthcare authorities to the people of their city and region.

Desire: Many locations have limited internet connectivity.  In these locations the user might go to an internet cafe, quickly visit the news, and then leave.  Later that day they would want to be able to reference that news from a site with no internet connection.  So the last downloaded news should be cached.

**Comment by murari85b7** [comment]
I can look into this issue. Please assign it to me.

**Comment by tstirrat** [comment]
Note: there might be more than one HCA active for a user at any time.  i.e. they may have added their own manual authority and they might be using the recommended one for their county/area/state

**Comment by Patrick-Erichsen** [comment]
Closing this issue out as we have taken it into consideration and documented the feedback on [this page in Jira](https://pathcheck.atlassian.net/wiki/spaces/SAFE/pages/81265028/GitHub+Issues+-+Community+Feature+Requests).
