### ISSUE TITLE
FEATURE: Select locale

### ISSUE THREAD

**Issue by penrods** [Path-Check/covid-safe-paths#263]
The current localization scheme uses the language of the phone to pick a locale.  However, some locations have a legal language, but many in the population actually speak a variation -- e.g. a creole.

Support this functionality by allowing the user to pick the Locale in the first page of the welcome sequence.  The local should be indicated by both text and (ideally) a Flag icon.  This is a small dropdown addition to the existing first page, not an extra page.

The Settings page should also allow switching locales.

**Comment by rparet** [comment]
I understand the need for this in places like Haiti. However, are we imposing this across the app? If yes, can we justify the additional onboarding friction for most customers? Is it possible to do this in a more elegant way than in the welcome sequence?

**Comment by penrods** [comment]
It will be a little dropdown, much like you see in websites.  Kinda like language picker in the upper right of this website:  https://www.similarweb.com/ja/website/nicovideo.jp

**Comment by penrods** [comment]
I updated the description to clarify that this isn't a completely new page, just a small addition to the existing first page.

**Comment by andreanuzzo** [comment]
How about a choice at the first launch of the app?

**Comment by saranyaharidas** [comment]
Looks like a duplicate issue ?

#355
