### ISSUE TITLE
Need to add checks when swiping pages backwards

### ISSUE THREAD

**Issue by talha7o** [Path-Check/covid-safe-paths#278]
When start logging, and stop logging, swipe backwards, in this page App is still logging.

**Comment by aartiverma1** [comment]
We checked multiple conditions here:
1) On 'start logging' button click, App is taking the coordinates and on 'Stop logging' button it has stopped taking coordinates. 
2) when application is killed or even in background it's still taking coordinates.
3) Bug we found was : Application started logging -> kill application -> start it again(Application is logging) -> Stop logging -> start logging ->Now application stops taking coordinates.
We can create a separate issue for that.

**Comment by ten-sis** [comment]
@aartiverma1 , could you please clarify what were you checking that indicated about locations not being logged in? 
Also, wanted to share that [the library we are using for location](https://github.com/mauron85/react-native-background-geolocation) has stationaryRadius set to 5 (meters) before it starts logging location. So, it might require the phone to change location before it starts logging

**Comment by denispapakul** [comment]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/47609057/81282820-60992500-9064-11ea-8a1c-edc785b2d366.gif)
Actually I set track location every second and I see that issue is not reproduced, cuz it's work after @aartiverma1 's steps

**Comment by denispapakul** [comment]
Actually, for me it's work fine. I set the delay for geo-tracking as 1 second for better the test experience.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/47609057/81541577-fa6e1400-937b-11ea-949a-cbf9f5d324ef.gif)

**Comment by denispapakul** [comment]
Actually, for me, it's working fine. I set the delay for geo-tracking as 1 second for better the test experience.

![Screen-Recording-2020-05-06-at-5](https://user-images.githubusercontent.com/47609057/81542289-13c39000-937d-11ea-9888-aa8cc30478e5.gif)

**Comment by summetj** [comment]
@talha7o , @aartiverma1  Can you provide more details about how to replicate this to show the bug?  (Or should I close the issue? There has been a lot of refactoring of the GPS logging codebase, and one of those might have fixed this issue....)

**Comment by talha7o** [comment]
This bug was reported in older version. App has matured alot and UI is all new now. Don't think reported bug is still valid now.

**Comment by summetj** [comment]
> This bug was reported in older version. App has matured alot and UI is all new now. Don't think reported bug is still valid now.

Cool, thanks for the confirmation, I'll close it out!
