### ISSUE TITLE
Feature: Broadcast based customized alert notifications/messages for users

### ISSUE THREAD

**Issue by tremblerz** [Path-Check/covid-safe-paths#300]
This could have further level of granularity in terms of specific message based on age, occupation and etc. The details like age and etc. won't go to the central server but only filtered at device.

**Comment by E3V3A** [comment]
Whoot? I don't get it... :( 
What is broadcasting, from what and to where?

**Comment by StartupSam** [comment]
@tremblerz Are you envisioning this kind of broadcast being published by local health authorities, us as the app administrators, or someone else?

**Comment by Patrick-Erichsen** [comment]
Closing this issue out as we have taken it into consideration and documented the feedback on [this page in Jira](https://pathcheck.atlassian.net/wiki/spaces/SAFE/pages/81265028/GitHub+Issues+-+Community+Feature+Requests).
