### ISSUE TITLE
Epidemiological simulation incorporated with a probabilistic model of Contact Tracing

### ISSUE THREAD

**Issue by tremblerz** [Path-Check/covid-safe-paths#302]
Study how efficacy varies with more diffusion of the app (% usage) and number of days the app is tracking (number of days).
Several other important parameters to consider as well.
See this paper for reference:
[Ferretti et al.](https://science.sciencemag.org/content/early/2020/03/30/science.abb6936)

**Comment by penrods** [comment]
To be clear, this isn't an App feature -- this is just potential work that could be done adjacent to this project, right?

**Comment by andreanuzzo** [comment]
@penrods yes, the work is supposed to help pitch the value of the app, not be deployed to the users. If we could use models to better predict the risk exposure in the overlap function is something to be discussed later. 

With the official release of the Ferretti et al. 2020 on Science after the previous Hellewell et all that I posted at the beginning, the case for advanced contact tracing is strong. Ramesh pushed for further data.

**Comment by Patrick-Erichsen** [comment]
Closing this issue out as we have taken it into consideration and documented the feedback on [this page in Jira](https://pathcheck.atlassian.net/wiki/spaces/SAFE/pages/81265028/GitHub+Issues+-+Community+Feature+Requests).
