### ISSUE TITLE
FEATURE REQ:  Automatic redaction algorithm for privacy sensitive geolocations.

### ISSUE THREAD

**Issue by tremblerz** [Path-Check/covid-safe-paths#304]
Assign a uniquely identifiable score for a pair of (user, geocoordinate). The higher the score is, the higher should be probability of removal of the points.

**Comment by penrods** [comment]
This also might make sense on the Contact Tracer side.  I think there is a balancing act of personal privacy and public health concern.  Perhaps we allow the user to decide to Share an auto-redacted (client side) OR to share a full history that they will go through with a trusted Contact Tracer.

**Comment by E3V3A** [comment]
@tremblerz 
>  The higher the score is, the higher should be probability of removal of the points.

Huh, what? Please elaborate. How and where does this probability function come in?

**Comment by andreanuzzo** [comment]
If we work by % time spent in the same place (i.e. house/office) we could suggest something like "hey, you spent a lot of time in this area, do you want to remove it from the shared records?" (or something better formulated)

**Comment by Patrick-Erichsen** [comment]
Closing this issue out as we have taken it into consideration and documented the feedback on [this page in Jira](https://pathcheck.atlassian.net/wiki/spaces/SAFE/pages/81265028/GitHub+Issues+-+Community+Feature+Requests).
