### ISSUE TITLE
FEATURE REQ: Ability to record location where sheltering post-diagnosis

### ISSUE THREAD

**Issue by penrods** [Path-Check/covid-safe-paths#333]
Not certain if this is a feature for the mobile app or Safe Places, but it makes sense to allow someone to report where they WILL be.  Here is the use case:

1) Individual gets diagnosed with COVID
2) If not seriously sick, they will be asked to stay at him while infectious
3) Knowing where the will most likely be can be valuable to First Responders, e.g. a firefighter who is on the way to the house where they are sheltering for an emergency.

**Comment by penrods** [comment]
This emerged from talks with governments.  Currently we only provide retrospective information - you crossed paths in the past.  This feature in some form could allow proactive notification.

The intention isn't for the general public to use this.  Presumably if I am self quarantining then I will not be interacting with them.  However, emergencies could break into that quarantine.  For example a fire starts or someone passes out and emergency personnel are called in to a residence to help.  This would give them a heads up to take extra precautions.

This does have privacy repercussions and it does not make sense until we get encryption built in.  I fear the "burn down the infected house" response, otherwise.

**Comment by Patrick-Erichsen** [comment]
Closing this issue out as we have taken it into consideration and documented the feedback on [this page in Jira](https://pathcheck.atlassian.net/wiki/spaces/SAFE/pages/81265028/GitHub+Issues+-+Community+Feature+Requests).
