### ISSUE TITLE
iOS Location Interval & Accuracy

### ISSUE THREAD

**Issue by jsmith** [Path-Check/covid-safe-paths#335]
Hi all!

Thank you so much for making this app :) I've been experimenting with it the past few days and just had a few points that I wanted to raise with regards to the background location tracking on iOS.

The location service [mauron85/react-native-background-geolocation](https://github.com/mauron85/react-native-background-geolocation) is currently being configured to have a high `desiredAccuracy`, `stationaryRadius` of 5 meters and `distanceFilter` of 5 meters. The `interval`, `fastestInterval` and `activitiesInterval` intervals are also being configured to 5 minutes; however, these are only for `Android`. What I observed is fairly constant logging while the app is in the foreground (this was in a simulator). This makes sense as, from I understand from the library documentation, it's using the Apple `standard location service` while in the foreground. With the settings describe above, this is how I would expect the app to behave. Right now, it doesn't seem like there is any logic to limit this data collection or to ensure that data isn't stored twice within a 5 minute interval. This relates to #230 I think.

I also wanted to raise the point of foreground vs. background location collection. In the [geolocation library documentation](https://github.com/mauron85/react-native-background-geolocation#switchmodemodeid-success-fail) it discusses the various modes of operations on iOS. If not configured using the `switchMode` method (which seems to be the case), it will use a combination of region monitoring and the `significant-change location service` while in the background and neither are terribly accurate (the accuracy can easily be less than 200 meters from what I understand). Is this the kind of accuracy that has observed while testing on iOS? I found I had a hard time testing background location so I'm not 100% confident on this.

Thanks again for this app!

Edit: small typo

**Comment by tstirrat** [comment]
We're looking into GPS accuracy etc: https://pathcheck.atlassian.net/browse/SAF-175

**Comment by Patrick-Erichsen** [comment]
Closing as per Tim's comment - we have ongoing work in-flight to improve our location tracking reliability and accuracy for both Android and iOS.
