### ISSUE TITLE
BUG - Main Menu UI elements overlap each other on IPhone SE

### ISSUE THREAD

**Issue by DavidMershon81** [Path-Check/covid-safe-paths#337]
device: iphone SE
OS: iOS 13.3.1

Description
"stop logging" and "check overlap" buttons overlap each other, and overlap text on main menu

Steps to Reproduce
- Download and open the app
- Scroll through the opening explanation screens until the main menu comes up

![private kit overlap](https://user-images.githubusercontent.com/63134933/78417125-ee0bd400-75e3-11ea-8d27-63bc1db77208.PNG)

**Comment by E3V3A** [comment]
Same on Android!

**Comment by jincepgeorge** [comment]
I have started working on this issue . Please assign to me

**Comment by jincepgeorge** [comment]
Screenshot from iPhone SE
![IMG_0018](https://user-images.githubusercontent.com/19973278/78759732-b3b48500-799d-11ea-9e01-73f1569388ef.PNG)
Same issue fixed for landscape mode too Landscape Screen1
![IMG_0019](https://user-images.githubusercontent.com/19973278/78759804-d6469e00-799d-11ea-8394-7910ad53ac20.PNG)
Landscape Screen 2
![IMG_0020](https://user-images.githubusercontent.com/19973278/78759838-de064280-799d-11ea-977a-c29d1041331a.PNG)

**Comment by DavidMershon81** [comment]
I'm still new to github, do I need to assign this since I opened the issue? I can't figure out how to do that.

**Comment by Patrick-Erichsen** [comment]
Closing as this PR is unrelated to Safe Paths. The screenshots above are from Private Kit.
