### ISSUE TITLE
Code clean-up for develop branch

### ISSUE THREAD

**Issue by tremblerz** [Path-Check/covid-safe-paths#353]
There is a lot of code sitting inside the app which is not being used and we should clean it up (NOTE: This doesn't include debug comments)
Example -
1. overlap.js and associated test files etc.
2. Encryption folder
3. Stylesheets that are not getting used.
4. Libraries which are imported but not used.
and many more (will add later)

**Comment by NethravathiPuttraju** [comment]
I can do Code Clean Up for develop branch.

**Comment by tstirrat** [comment]
We've done plenty of cleanup on `develop`
