### ISSUE TITLE
Implement more scalable solution to translations

### ISSUE THREAD

**Issue by kenpugsley** [Path-Check/covid-safe-paths#357]
Reference to the PR where this came up:  #356 

We should come up with a more scalable solution for handling translations, ideally something that will allow translators to easily access the file(s) they need, along with needed comments or instructions so that translators can easily understand what section needs to be worked on or has been updated.  

Not proposing any solution at this point.

**Comment by Patrick-Erichsen** [comment]
Closing as we are now using Lokalise.
