### ISSUE TITLE
Main.js/LocationTracking.js process teardown/leak warning

### ISSUE THREAD

**Issue by tstirrat** [Path-Check/covid-safe-paths#373]
Narrowed down to LocationTracking.spec.js

```
PASS  app/views/__tests__/LocationTracking.spec.js
  ✓ renders correctly (67ms)

  console.log app/views/LocationTracking.js:133
    Can't find crossed paths

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   1 passed, 1 total
Time:        2.755s, estimated 4s
Ran all test suites matching /locationtracking/i.

Watch Usage: Press w to show more.A worker process has failed to exit gracefully and has been force exited. This is likely caused by tests leaking due to improper teardown. Try running with --runInBand --detectOpenHandles to find leaks.
```

Something is not doing async or teardown correctly.

**Comment by kenpugsley** [comment]
Not necessarily easy, but a good issue for someone new wanting to join the dev team.

**Comment by lewisPrescott707** [comment]
I can take a look at this one? I am a QA by trade, so would be interested in looking at this one

**Comment by summetj** [comment]
@lewisPrescott707  - All yours. Note that a lot has happened to the codebase in the last month, so verify the issue still exists.

**Comment by lewisPrescott707** [comment]
Been looking at this for a little while now and can't find the issue. Running `--detectOpenHandles` doesn't return anything.

Found this, could we add `--forceExit` like suggested?

[Jest Issue](https://github.com/facebook/jest/issues/1456#issuecomment-609367298)

**Comment by tstirrat** [comment]
I'd prefer not to add a "hammer" solution.. vs trying to identify/mock each dependency and use `jest.useFakeTimers()` etc.

Note that since #749 we care more about tests working in [Main.js](https://github.com/Path-Check/covid-safe-paths/blob/develop/app/views/Main.js) and the sub components in [main/*](https://github.com/Path-Check/covid-safe-paths/tree/develop/app/views/main), as LocationTracking.js will be removed soon enough.

**Comment by tstirrat** [comment]
@lewisPrescott707 could you add some tests around the components in [main/*](https://github.com/Path-Check/covid-safe-paths/tree/develop/app/views/main) and see if this issue still shows? 

the recent component separation may help us isolate the problem to a specific view and dependency.

**Comment by tstirrat** [comment]
If the warning doesn't show anymore, we can commit those tests and close this

**Comment by lewisPrescott707** [comment]
Found the specific dependency causing the leak, adding tests for main/ helped me isolate it!! Thanks @tstirrat

**Comment by summetj** [comment]
> Found the specific dependency causing the leak, by adding tests for `main/`, they helped me isolate it!! Thanks @tstirrat

Great work, thanks!
