### ISSUE TITLE
CONCERN: App delivers "green" status when in fact it has no data.  DHM-S1-1 

### ISSUE THREAD

**Issue by diarmidmackenzie** [Path-Check/covid-safe-paths#442]
https://docs.google.com/document/d/1Uh1A-h7Ddm6t-rAlHOM90xnsrkLEG9SGcTolf3uIbgQ/edit

The app generates false positives by default.  It defaults to a “green” status when in fact no data has been collected.  This risks giving people false confidence that they are uninfected and could have a negative impact on their behaviour.

The text "Based on available data you haven't been near anyone reported positive for COIVD-19" is deeply misleading when there is in fact no available data.

Suggestion is that we have a 3rd status: "No info yet", which encourages the user to register with a health authority.  A percentage indicator showing how much info the user has might also work well.

**Comment by summetj** [comment]
This is very similar to #434 @tremblerz but fully defined.  If this behavior is still a concern I'd like to close #434 and try and get somebody to work on this one.   On the other hand, I believe this behavior is correct w.r.t. the specifications document, so the issue should be brought up as an improvement for the next specification document and not a correction to the codebase.

**Comment by summetj** [comment]
According to the MVP specification, the app should display "No Exposure data is available yet" if no health authority is selected, and the "No known contact" screen only IF a health authority is selected. This is not currently the behavior for version: 1.0.0

**Comment by tstirrat** [comment]
This has been fixed in 1.0.x
