### ISSUE TITLE
BUG: Poor user experience if the user chooses “don’t ask me again” when denying permission or locations - DHM-S-1-7

### ISSUE THREAD

**Issue by diarmidmackenzie** [Path-Check/covid-safe-paths#448]
Behaviour if user denies permissions on location is much better than in V0.5.12, but still not perfect.

 [DHM-S1-7] Poor user experience if the user chooses “don’t ask me again” when denying permission – user just gets repeated notifications that the app needs to access location info, but gets no guidance how to get out of this situation (they need to go deep into the settings menu & explicitly adjust the permissions).

Pretty minor issue, and not obvious how to do better.

However I can see a user misreading the location access request, and then getting into this state & not knowing how to get out - so worth considering if we want to give the best possible UX for all possible users.

**Comment by E3V3A** [comment]
Can we check on each start and then warn the user if it is still unset?

**Comment by summetj** [comment]
This is still an issue in the released 1.0 app, but I do not feel it is a critical issue. 

I expect the android and iOS flow/permissions (and solutions) may be slightly different.   [I don't even know if there is a way for us to detect that the user isn't pushing the "deny" button, but instead the OS is auto-denying the permission request.]

I don't necessarily want to say we won't fix this, but this could be a thorny issue that can't be fixed, and it only rears up if the user both denies location permissions, AND clicks the "do not re-ask" when doing so.

**Comment by Patrick-Erichsen** [comment]
Closing this issue out as we have taken it into consideration and documented the feedback on [this page in Jira](https://pathcheck.atlassian.net/wiki/spaces/SAFE/pages/81265028/GitHub+Issues+-+Community+Feature+Requests).
