### ISSUE TITLE
POSSIBLE BUG: Import of Location history from Google fails on at least some devices - DHM-S1-8

### ISSUE THREAD

**Issue by diarmidmackenzie** [Path-Check/covid-safe-paths#449]
I was not able to get this function to work, despite following all on-screen instructions.
o   Within the embedded Google Account pane, I was able to export & download my location history.
o   After that, instructions were to “open this screen again.  The data will import automatically”.  I tried to do this many times, but did not succeed.  I don’t know whether that’s a functional issue or a UX issue.

Notes in https://github.com/tripleblindmarket/covid-safe-paths/issues/69 suggest that other users have managed to get this to work (though they lamented the user experience).

So I don't know what the issue was with my phone.  Please let me know what diags would be useful and I'll aim to provide.

Note that this is one of the key basic functions of the App, so if it's not working on some devices, that seems like a serious concern.

**Comment by diarmidmackenzie** [comment]
This may be due to having multiple google accounts on the phone I was testing with.  If so, then it's a rare case and hence less critical.

One account is the "primary" account on the phone, but I tried to download location data for a different google account.

I have been changing these settings around a bit (for personal reasons unrelated to my testing) - probably next step is to explore this and see if I can find a way to make it work, and what I need to change to stop it from working.

**Comment by E3V3A** [comment]
IMO. We should not be dependent on having an Google email account at all. Most people have multiple emails and multiple phones, for diff purposes, so this (location service) dependence is basically blocking them from using this.

**Comment by diarmidmackenzie** [comment]
@kenpugsley Are you able to tell me what conditions need to be satisfied for the import to work?  I'd like to try & diagnose why this is still not working on my system.

I believe the app is looking for a certain file, which it expects to find iun a certian directory?

I have a file called takeout-20200411T222013Z-001.zip in my Download folder.  What might be stopping the app from picking this up?

**Comment by diarmidmackenzie** [comment]
Agree with @E3V3A that the correct thing to do here is really to address this one:
https://github.com/tripleblindmarket/covid-safe-paths/issues/69

(even more so after having witnessed my wife struggle through the interface, see latest notes in #69)

If we can do that soon, we can save some hassle & drop this one.  But if we aren't going to get to that one soon, then we probably have to work through the apparent reliability issues here.

Perhaps a 1st step is some design analysis on #69 - are there other viable mechanisms?  Does Google offer an API & could we integrate to it?

Once we understand the scale of '69, then we'll have a better idea whether it's worth focussing on the current implementation at all.

**Comment by kenpugsley** [comment]
I honestly haven't tried to use this function in the app.  @tstirrat @tremblerz might be able to answer regarding the conditions required for this to work.

Also, be aware that #410 is currently in progress to rework this import process.

**Comment by anigasan** [comment]
I am facing this issue when I tried with Samsung Note 8. I don't see any import button after Google Takeout Export

**Comment by diarmidmackenzie** [comment]
This whole area is being reimplemented from scratch after #410 so lets leave for now & come back when #410 is done.

**Comment by anigasan** [comment]
OK, Let us keep this thread open!!

**Comment by tremblerz** [comment]
Can folks start testing it again please

**Comment by diarmidmackenzie** [comment]
This is not working for me.  v0.9.5 Android 9 Moto G7.

I can get the TAKEOUT (UX is improved).

Then I go to IMPORT LOCATIONS, navigate to the file on Drive or Local files (tried both).  I see a file called takeou-202...., 164kB in size.

I select it, and immediately return to the "Import Locations" screen.  No indication whether it has succeeded or failed - which is a poor UX - I'd expect an indication either way.

When I go to: Share Location History, and Share location data, then I see that the file attached to the email is only 1kB, which suggests to me that I only have the data from when I installed the app, and not the 164kB of data that was in the Takeout.

Am I following the process correctly?  Any diagnostics that I could provide that would be helpful?

**Comment by brunaevaldt** [comment]
This is not working for me either. v. 0.5.19 IOS 13.3.1 iPhone Xr

I also have 2 google accounts on my device, but when I got the Google take out screen, I logged in with the primary one.

* I tap on the top right menu
* Tap on the button "Import past locations"
* After I login and tried a couple of times to export my location history, I see the download options:

![IMG_1693](https://user-images.githubusercontent.com/14109590/80006740-9adfbf80-84c5-11ea-9424-2ef6bfd9c08e.PNG)

When I click on "download", I get this: 

<img width="286" alt="Screenshot 2020-04-22 at 18 26 34" src="https://user-images.githubusercontent.com/14109590/80007674-e050bc80-84c6-11ea-99f4-1844e34b163f.png">

**Comment by kenpugsley** [comment]
@brunaevaldt that appears to be from Private Kit.  Private Kit has been split of, and it now located here:  https://github.com/PrivateKit/private-kit

**Comment by brunaevaldt** [comment]
@kenpugsley I followed the onboard e-mail, where we are asked go to the [website](https://covidsafepaths.org/) and install the [app](https://apps.apple.com/us/app/private-kit-prototype/id1501903733). Is this the correct link to install the app? or did I miss something?

**Comment by summetj** [comment]
> @kenpugsley I followed the onboard e-mail, where we are asked go to the [website](https://covidsafepaths.org/) and install the [app](https://apps.apple.com/us/app/private-kit-prototype/id1501903733). Is this the correct link to install the app? or did I miss something?

That is the app currently in the app store, but not the latest development apk which should be installed from github. 

(The welcome email is directed to everyone, including developers, so we ask them to install the latest "app-store" released application).

For testing/development, you probably want to be using the latest release found under the "releases" in github here:
https://github.com/tripleblindmarket/covid-safe-paths/releases

I will update the developer readme document to highlight that the location of the latest releases for developers is on github.

**Comment by summetj** [comment]
#410 is finished. Can somebody (@diarmidmackenzie  ?)  please re-test this issue with the 1.0.1 release and report back if I can close this ticket?

**Comment by diarmidmackenzie** [comment]
Import of Google Takeout is still not enabled in v1.00 or v1.0.1 as it is currently considered "not good enough".

Probably we should ensure this function is tracked as a Jira story, for PM to schedule as appropriate,  & close this.

**Comment by summetj** [comment]
Ok, I'm closing the issue, @diarmidmackenzie I'll let you set up the function in Jira to schedule/track for future enhancement so we can keep the github issues specific to issues with the current code.
