### ISSUE TITLE
CONCERN: Privacy concern over e-mail as mechanism for sharing location history DHM-S1-13

### ISSUE THREAD

**Issue by diarmidmackenzie** [Path-Check/covid-safe-paths#453]
https://docs.google.com/document/d/1Uh1A-h7Ddm6t-rAlHOM90xnsrkLEG9SGcTolf3uIbgQ/edit

  [DHM-S1-13] Privacy concern.  I am offered many options for how to share my data, but the default option is via email.
o   Having shared via email, my unencrypted, unredacted location history is now stored indefinitely in both my “sent items” folder, and in the mailbox of the Healthcare Authority I sent it to.
o   This seems inconsistent with the stated privacy aims of the project (and e.g. with the policy to delete location data after 28 days).

**Comment by summetj** [comment]
This is a valid concern, but in the interests of ease-of-use and interoperability we are supporting email transfer of the data. (along with other transports). 

If an attacker has access to your own email you might have bigger issues to worry about than them knowing your location history. [And the same applies to the Health Authority.]

At at some point in the future it would be nice to add the ability to transfer the data directly to the HA SafePlaces application via an encrypted transport (as well as allowing the user to redact data on their phone before transferring....)

**Comment by diarmidmackenzie** [comment]
"If an attacker has access to your own email you might have bigger issues to worry about than them knowing your location history."

You might, and you might not.  Lots of different possible attackers, not all sinister strangers.

A husband or wife might easily be trusted to have access to your email account (or be able to get access fairly easily).  That doesn't mean you are happy for them to view your location history.

**Comment by summetj** [comment]
@diarmidmackenzie Agreed, secure transmission of location data is definitely a desirable feature.

**Comment by Patrick-Erichsen** [comment]
Closing this issue out as we have taken it into consideration and documented the feedback on [this page in Jira](https://pathcheck.atlassian.net/wiki/spaces/SAFE/pages/81265028/GitHub+Issues+-+Community+Feature+Requests).
