### ISSUE TITLE
BUG: Non-email sharing options for location history don't provide any context DHM-1-17

### ISSUE THREAD

**Issue by diarmidmackenzie** [Path-Check/covid-safe-paths#455]
https://docs.google.com/document/d/1Uh1A-h7Ddm6t-rAlHOM90xnsrkLEG9SGcTolf3uIbgQ/edit

[DHM-S1-16 - New ] Sharing by email adds some useful context to the message “Here is my location log from Private Kit”.  However, sharing by other means (WhatsApp, Google Drive) just dumps an JSON file with a cryptic filename, with zero context).

I don't know what options there might be for providing more context for these other sharing mehcanisms?

Or maybe we don't care about offering them.  If so, can we restrict them so that only e-mail is available?

In any case, as per #453 , maybe sharing should be handled natively in-app for privacy reasons anyway?

**Comment by E3V3A** [comment]
You send 2 messages, 
1. with the contect description, "The next message will be a file."
2. The file!

**Comment by summetj** [comment]
This would be a good self contained issue for somebody to work on. Pick a specific transport (such as WhatsApp) and figure out how to add a subject "Covid Safe Paths Location trace data" when sending the export file with it.)

Then repeat for the top "X" transports.

**Comment by diarmidmackenzie** [comment]
However I believe we are working on a more secure transport channel to send data direct to the HA, in which case this issue may become moot.

**Comment by diarmidmackenzie** [comment]
Hmm.  Not convinced we should be supporting HAs in depoying privacy-deficient implementations.

Retaining this function when no longer required would violate the "minimize attack surface area" Security by Design principle.

**Comment by Patrick-Erichsen** [comment]
Closing this issue out as we have taken it into consideration and documented the feedback on [this page in Jira](https://pathcheck.atlassian.net/wiki/spaces/SAFE/pages/81265028/GitHub+Issues+-+Community+Feature+Requests).
