### ISSUE TITLE
BUG: “COVID Safe Paths Enabled” notification about storing GPS data. cannot be dismissed - DHM S1-30

### ISSUE THREAD

**Issue by diarmidmackenzie** [Path-Check/covid-safe-paths#473]
https://docs.google.com/document/d/1Uh1A-h7Ddm6t-rAlHOM90xnsrkLEG9SGcTolf3uIbgQ/edit 

After installing the app, I have a “COVID Safe Paths Enabled” notification about storing GPS data.

This cannot be dismissed.  My only option is to “minimize” the notification, but this seems to have no effect.

(I believe as a result) the SafePaths app always has a small purple dot in the top right corner indicating notifications.

This could be annoying to an end user, potentially even to the point where they might uninstall the app.

Is there a good reason why this Notificaton can't be dismissed?

**Comment by tremblerz** [comment]
I think the App which log location constantly need to show this notification and I am not sure if we can get rid of it. Need someone to get into details and see if it is possible and how to do it.

**Comment by E3V3A** [comment]
> I think the App which log location constantly need to show this notification

no, most other GPS loggers only show this once, if at all

**Comment by aartiverma1** [comment]
I can look into this.

**Comment by diarmidmackenzie** [comment]
Just a note on impact - I am now running Private Kit+ Safe Paths together, and my notifications tray is almost unusable because both of these are in it, non-dismissable, and blocking me from seeing other notifications.

If I was not working on the product I would be deleting at least one of them!

**Comment by aartiverma1** [comment]
A Detailed Analysis : The persistent notification is required by Android foreground services.
When BackgroundGeolocation.start() was executed, the Android SDK would launch a foreground-service (along with its required persistent notification). The foreground-service would remain running with its persistent notification until BackgroundGeolocation.stop() was executed. So we can't get rid of persistent notification.

**Comment by Patrick-Erichsen** [comment]
Closing this issue out as we have taken it into consideration and documented the feedback on [this page in Jira](https://pathcheck.atlassian.net/wiki/spaces/SAFE/pages/81265028/GitHub+Issues+-+Community+Feature+Requests).
