### ISSUE TITLE
For testing, we need an easy way to check if the phone is logging location on a regular cadence

### ISSUE THREAD

**Issue by diarmidmackenzie** [Path-Check/covid-safe-paths#489]
Thinking about how to test this:
https://github.com/tripleblindmarket/covid-safe-paths/issues/454

Chris Wren suggestion of scanning across a large volume of test data from multiple phones is great, but we'd need some tooling to do it.

I can see 2 approaches here that could work:

1. we write a script that checks a set of exported logs for deviations from the expected cadence.  We ask all testers to regularly export their logs & send them to a common email address.  Then we run this script over all collected logs, to identify any bugs.  Handling of emails etc. can potentially be automated, but could start out manual.

2. We build something natively into the app, so that when it wakes up to log location, it checks the time, compares it with the last log time, and self-diagnosis an issue.  In some ways that's a lot simpler than 1 (no wrangling with loads of emails), but there are other challenges: how does an app that has self-diagnosed a problem report this?  Does it write out some error log?  Who collates & monitors those error log files?  Are these error log files only generated for internal test builds, or do they run in production as well?

2 feels like a more powerful & extensible overall framework.  Perhaps such logging infrastructure exist already in the app?

* If so feels like we should leverage this to solve this problem, rather than implementing solution 1.  We should also be briefing testers on how to check the error log files on their app (and/or centralizing collation of these log files).

* if not, should we consider adding it?  I assume there are standard frameworks to do all this, so we should be able to get a suitable framework off the shelf...

**Comment by summetj** [comment]
Due to the sensitive nature of the data the app is collecting (location logs, potentially contact ID's in the future) we will want to be very careful with the amount/type of diagnostic data we collect. [I would recommend we do all testing ourselves instead of instrumenting the app.]

**Comment by diarmidmackenzie** [comment]
If we are succesful, millions of people will instal this app, and run it for billions of hours.

Total hours of internal testing will probably be in the thousands.

It is inevitable that they will run into important problems, which we should fix, which it would be impossible to find in our own internal testing.

Creating a privacy-respecting plan for how we address this fact is a major challenge, but let's not kid ourselves that we will find all problems in our own testing.

**Comment by Patrick-Erichsen** [comment]
Closing this issue out as we have taken it into consideration and documented the feedback on [this page in Jira](https://pathcheck.atlassian.net/wiki/spaces/SAFE/pages/81265028/GitHub+Issues+-+Community+Feature+Requests).
