### ISSUE TITLE
Put notification if location is not getting logged

### ISSUE THREAD

**Issue by tremblerz** [Path-Check/covid-safe-paths#50]
The location might not be getting logged due to the location turned off through settings or some other reason. We need a rigorous way of testing it.

**Comment by tushar-dadlani** [comment]
How aggressively do you want to notify the user?

**Comment by tremblerz** [comment]
We have push notifications now for iOS. On Android they still don't appear

**Comment by penrods** [comment]
Still an issue?

**Comment by summetj** [comment]
Yes lack of notification is still an issue on android. When running and logging in background, if locations permission is removed, there is no notification. (However, if the app is manually re-started, it detects that it needs to ask for location access again and goes through the "getting started" flow.)

**Comment by maher1719** [comment]
Maybe we can find the location with the network tower id who provide mobile signals and check the id with remote tower database

**Comment by Shabanisimo** [comment]
The bug is fixed.
