### ISSUE TITLE
Pivacy concern.  Not possible to install Safe Paths on multiple accounts on the same phone - I guess because we are not storing data in a per-user location.

### ISSUE THREAD

**Issue by diarmidmackenzie** [Path-Check/covid-safe-paths#563]
I think this merits some consideration.

Some info on the use cases for multiple user accounts.
https://www.guidingtech.com/android-multiple-users-feature/

I'm not sure there's actually a hard requirement to be able to install the app on multiple accounts.   That seems niche.  But I suspect that the problem is caused because we are storing app data in a location that is not user-specific.  And I have concerns about the Privacy implications of that design.

## Version

Android 9, Moto G7

I have 2 different user accounts on the phone.  It's a situation I got into by accident, and have been meaning to sort out, but hadn't got round to doing so.

## Steps to reproduce

On a phone with 2 Android user accounts.
- Install Safe Paths on one account via APK sideloading
- Attempt to Install Safe Paths on 2nd account  via APK sideloading

Install fails.  The failure messge doesn't give any detail.  It looks the same as the error when you try to install an APK without removing the previous version.

Indeed I guess that's exactly what we are doing: storing the data in a global location, rather than a per-user location.

Note: with 2 accounts, you can install Safe Paths on either account (doesn't have to be the admin account).  But the other account then can't install the app.

## Expected Behavior

I woudl expect multiple users of the same phone to all be able to install the app.

That is the behaviour I see with other apps.

I don't know a lot about the use cases Google envisage for multiple user accounts per-phone, but I assume they developed the function to meet the needs of some users.  It's reasonable to assume that those users might want to run Safe Paths.

I am also concerned about potential Privacy issues if we are not storing the data in a user-specific location:
- It is certainly possible for user B to determine that user A has installed the Safe Paths app, by trying to install it himself.
- If the data is in a global location, I wonder if there is any risk that user B could extract location data recorded by user A?

**Comment by diarmidmackenzie** [comment]
OK - here's a relevant use case, which merits consideration in the long run.

In the short term, I'm only concerned about the Privacy issues flagged above.

Teen breaks phone
Teen wants to go out at night.  Parent not happy for Teen to go out without a phone.
Parent lends Teen phone.  Parents does not want Teen to have access to their account, so creates a 2nd account for Teen on the phone.
Family is COVID-aware, so of course they want to install Safe Paths on this new account.

Ideal behaviour would be:
- Install succeeds
- Safe Paths notices that the phone has multiple accounts, and gives explicit warning that location data is per-account, and is only stored on the phone, so if they want to check their exposure later, then need to check it in Safe Paths *in this account*  (this way Teen knows that they will have to come back & check periodically, rather than assumign they will be notified).

This use case is not a priority for MVP, but eventually we should be aiming to accommodate use cases like this.

**Comment by diarmidmackenzie** [comment]
On a related note we should think about communications on this topic.

When e.g. Ramesh talks about privacy, the focus is on "the daat doesn't leave your phone".  That covers Privacy from the authorities.

But will that messaging resonate with someone who shares a phone with someone else?  Probably not?  Should we be ore careful to cover "the data does not leave your account, on your phone" to bring these people in?

(once that is true, obviously!)

**Comment by penrods** [comment]
This application does assume the most common use case -- a phone is associated with an individual.  Automated background operation with multiple individuals is basically impossible.  If you have specific suggestions to make it possible, it would be appreciated.  But I don't see this as solvable.

**Comment by summetj** [comment]
Moving the data store to the user's account location (as opposed to global phone storage location) for privacy protections (in the case of encrypted user storage as opposed to full phone encryption) might be worthwhile in the short term. 

I don't know enough about the android multi-user-accounts model to know if switching from one user account to a different one will automatically close down an app running in user A's account and then start up the background logging of the same app in user B's account, but I can easily see it as not solvable.
(On the other hand, I wouldn't be surprised to find an API that apps can use to detect user account switches and gracefully handle this situation.). I'm marking this low priority and next next release as I don't think we'll be working on user account switching soon.

**Comment by diarmidmackenzie** [comment]
I would say with a multi-user account, the desirable behaviiour on switching accounts is to shut down & stop logging location info on the 1st account & start on the 2nd.

See example above about a Teen borrowing Parent's phone to go out.

If the Teen is later infected, we want to share the Teen's movements.  If the Parent is infected the Parent's movements.

We are using phones as proxies for people.  But phone user accounts are actually a better match.


If we can't fix this, we should consider a nicer error message: "Sorry we can't support this operation at the moment"

Analytics so we know how often its happening would also be great, but I don't know how whether we can do analytics in a way that is consistent with privacy.

**Comment by penrods** [comment]
I've honestly never heard of this capability.  Is this common?  How does one do it?  In a brief search I couldn't find the capability on my Samsung (which often diverges from stock Android, I do realize).

**Comment by diarmidmackenzie** [comment]
Been available since Android 5.0.  Function is pretty much the same as you have with multiple users on e.g. Windows.

Some links here:
https://www.androidcentral.com/lollipop-brings-proper-multi-user-accounts-your-phone
https://www.guidingtech.com/android-multiple-users-feature/

I don't have any data on prevalence - I will ask around to see if anyone knows where to get such info. 

I didn't intentionally test this.  I have a 2nd user account on my phone for some reasons completely unrelated to this project, and happened to stumble across this issue.

I don't think it's a "must have" feature by any means, but the Privacy implications of storing what is logically user data in the wrong place in the Android architecture worry me a bit.  And I also worry this might be a lot more expensive to fix later, rather than now.  (fixing later, we'll have to migrate data from one place to another on upgade, which sounds tedious).

**Comment by diarmidmackenzie** [comment]
![Screenshot_20200420-134124](https://user-images.githubusercontent.com/16045703/79747995-eac75680-830c-11ea-97dd-529d20c6c6ce.png)

Where is it?  In settings see the little blue person/face at the bottom

**Comment by Patrick-Erichsen** [comment]
Closing this issue out as we have taken it into consideration and documented the feedback on [this page in Jira](https://pathcheck.atlassian.net/wiki/spaces/SAFE/pages/81265028/GitHub+Issues+-+Community+Feature+Requests).
