### ISSUE TITLE
Confusing notification text on "stop logging" action

### ISSUE THREAD

**Issue by summetj** [Path-Check/covid-safe-paths#564]
## Version 0.5.19 private kit from play store, verified exists in development code as well. 

- Type of phone: Android 
- OS Version: 9
- Model: Moto X4

## Steps to reproduce

Tap settings icon in top left to get to the dashboard
Tap the "stop logging" button.

Notification text reads: "Location tracking was Disabled" (good) followed by "PrivateKit requires location services" (technically true, but confusing, as it implies the app does not have access to location services.)

## Expected Behavior

Suggest we change the second line to: "Stopped at user request" in the case tracking was disabled by the user as opposed to the loss of location services. [Or just "Stopped" if the stop action can be triggered by things outside of user requests...]

![Screenshot_20200418-063118](https://user-images.githubusercontent.com/11669847/79635596-d4b86b00-813f-11ea-84d5-8b1d8c840055.png)

I suspect this is caused by a lazy reuse of the label.location_disabled_message in the app/services/LocationService.js file for both the stop action and the checkStatus action.

Suggested fix: Add a new label "location_stopped_message", get it translated for all languages, and differentiate between a stop action and an "if (!locationServicesEnabled)" check failure.

**Comment by aartiverma1** [comment]
I can start looking this issue.

**Comment by tremblerz** [comment]
yes please
