### ISSUE TITLE
Missing Step In Onboarding - Add A Healthcare Authority

### ISSUE THREAD

**Issue by Patrick-Erichsen** [Path-Check/covid-safe-paths#588]
## Version

- Type of phone: N/A
- OS Version: N/A
- Model: N/A

## Steps to reproduce

Right now the onboarding process does not include the screens to add a Healthcare Authority.

Walkthrough the onboarding process and you will not be directed to a screen that allows you to add a Healthcare Authority

## Expected Behavior

When going through the onboarding process, after enabling location services, I should be directed to a screen that allows me to select Healthcare Authorities in my area.

**Comment by saranyaharidas** [comment]
I can look into this one.

**Comment by summetj** [comment]
> I can look into this one.

Sounds good. Could this be a decision to omit initially until we have more healthcare authorities onboard to pick from? It is likely that a random person installing the app may not have an appropriate health authority to pick initially.
