### ISSUE TITLE
User is not notified if location is not enabled after onboarding

### ISSUE THREAD

**Issue by tremblerz** [Path-Check/covid-safe-paths#602]
## Version
- Model: Pixel 3 API 29

## Steps to reproduce

Turn the location off and install the App. Even though the app gets permission to "log all the time" during onboarding it never turns it on. User has to explicitly turn it on by going to settings or in the notification drawer

**Comment by shilpashendre** [comment]
I can start looking this issue.

**Comment by ten-sis** [comment]
I have been considering giving this issue to some dev who is currently looking for the work. @shilpashendre, if you are in progress or still willing to take care of this - let me know.

**Comment by tstirrat** [comment]
This is likely covered in #749

**Comment by summetj** [comment]
> This is likely covered in #749

I've linked it so 749 will close this issue.
