### ISSUE TITLE
Unknown status (due to location permission disabled) disappears on clicking on Settings

### ISSUE THREAD

**Issue by tremblerz** [Path-Check/covid-safe-paths#603]
## Version

- Model: Pixel 3 API 29

## Steps to reproduce

Install the app, onboard like a nice person and then go to settings, disable the location permissions to the App. Go back to the App, you will see "Unknown status" and then tap on settings, dashboard appears which shows Location active (**Shouldn't be**) and you go back it shows standard "No known contact"

## Expected Behavior

Tapping on settings shouldn't have changed any state and settings drawer should have shown "Location inactive"

**Comment by shilpashendre** [comment]
I can start working on this issue.

**Comment by summetj** [comment]
https://github.com/tripleblindmarket/covid-safe-paths/pull/631
