### ISSUE TITLE
1 and 2nd screen present in the ios app

### ISSUE THREAD

**Issue by ShreyaaSahu** [Path-Check/covid-safe-paths#611]
## Version 0.9.5

Type of phone: IOS
IOS Version: 13.3
Model: e.g. iPhone XR

## Steps to reproduce

1. First Launch : click on App Icon
2. App will move the user to all the 3 intro screens.

![IMG-4517](https://user-images.githubusercontent.com/64080646/79866017-c006fc00-83f9-11ea-86e2-2b04220e7d27.PNG)
![IMG-4518](https://user-images.githubusercontent.com/64080646/79866026-c4331980-83f9-11ea-94ee-fd92122ac4d5.PNG)
![IMG-4519](https://user-images.githubusercontent.com/64080646/79866033-c6957380-83f9-11ea-9a76-b70d6805cb28.PNG)

## Expected Behavior
Only One 3rd one instead of all three 
![IMG-4519](https://user-images.githubusercontent.com/64080646/79866033-c6957380-83f9-11ea-9a76-b70d6805cb28.PNG)

**Comment by kuzahaha** [comment]
Can you please give more detailed description of this issue, maybe expected and actual screens, thx.

**Comment by dganzi** [comment]
Is this describing the text cutoff?

**Comment by ShreyaaSahu** [comment]
This issue was raised as per the MVP req doc , There it was written like , only one  (3rd one )   onboarding screen instead of 3 should be present .

**Comment by summetj** [comment]
Per UI/UX channel on slack, the app should have 3 screens here (not sure if the MVP document is now out of date, but all the UI/UX people are using Figma and say that 3 screens is correct w.r.t. that.
