### ISSUE TITLE
No Known Contact / No Data match Screen - Issues 

### ISSUE THREAD

**Issue by ShreyaaSahu** [Path-Check/covid-safe-paths#612]
## Version 0.9.5

- Type of phone: iPhone
- OS Version: 13.3
- Model: e.g. iPhone XR

## Steps to reproduce

1. Click on App icon 
2. tap on "get started "
3. set the location 
4. tap on " Finished Setup "
5. next screen will be the " No Known Contact " with green check sign.
6. displaying "Based on available data you haven't been near anyone reported positive for COVID-19. "

![IMG-4520](https://user-images.githubusercontent.com/64080646/79869073-7c62c100-83fe-11ea-9d7e-219249005487.PNG)

## Expected Behavior

1.  Grey colour instead of green as per MVP Requirement  doc 
2. "No Data Match " and " Based on selected data sources, there is no data match at this time. "  instead of " No Known Contact " and  "Based on available data you haven't been near anyone reported positive for COVID-19. "

 in version 0.9.3 it was grey

![IMG-4497](https://user-images.githubusercontent.com/64080646/79869186-a74d1500-83fe-11ea-87c5-44b939af11ee.PNG)

**Comment by ArchanaNair** [comment]
This is linked with issue #607, I am working on it. Please assign it to me.

**Comment by dganzi** [comment]
Duplicates #607.

**Comment by summetj** [comment]
Linked to #673.

**Comment by summetj** [comment]
@ArchanaNair  - Let me know if this issue still applies or not after you communicate with the ui/ux people.

**Comment by ArchanaNair** [comment]
@summetj , sure have dropped a message to @driedgrape, will update here once it is confirmed.

**Comment by ArchanaNair** [comment]
@summetj  You can close this as the issue is not valid as per @driedgrape
