### ISSUE TITLE
[Choose health authority] - View title not fully visible 

### ISSUE THREAD

**Issue by ilonadynska** [Path-Check/covid-safe-paths#618]
## Version - 0.9.5

- Type of phone: Android 
- OS Version: 9.0, 10.0
- Model: Samsung A50, Samsung Galaxy S10

## Steps to reproduce
1. From home tap the right top setting button 
2. Tap on Choose health authority 

Applies to following languages:
- Spanish
- French
- Italian
- Dutch
- Polish
- Russian

## Expected Behavior

Title should be fully visible. 

![Screenshot_20200422-002247_COVID Safe Paths](https://user-images.githubusercontent.com/59801345/79924518-3f1b2500-8438-11ea-8447-65c5525d6bbe.jpg)

**Comment by ilonadynska** [comment]
@tstirrat can we make the font smaller or fit the space (or truncate) or we should involve each translator to modify the text and (if possible) make it shorter?

**Comment by NethravathiPuttraju** [comment]
I can look into this. @tstirrat  can you give your suggestions .

**Comment by NethravathiPuttraju** [comment]
Can anyone give suggestion which solution will be better , reducing the font or truncate the text..

**Comment by tstirrat** [comment]
@alpita-masurkar and @penrods will probably have thoughts here. Thanks for checking

**Comment by Patrick-Erichsen** [comment]
Closing as we have UI/UX work in flight to refactor this screen.
