### ISSUE TITLE
[Choose health authority] - White background table 

### ISSUE THREAD

**Issue by ilonadynska** [Path-Check/covid-safe-paths#620]
## Version - 0.9.5

- Type of phone: Android 
- OS Version: 9.0, 10.0
- Model: Samsung A50, Samsung Galaxy S10

## Steps to reproduce
1. From home tap the right top setting button 
2. Tap on Choose health authority 

Applies to all the languages.

## Expected Behavior

Background behind 'No data source yet' lable should be the same of the view.

![Screenshot_20200422-002247_COVID Safe Paths](https://user-images.githubusercontent.com/59801345/79924518-3f1b2500-8438-11ea-8447-65c5525d6bbe.jpg)

**Comment by NethravathiPuttraju** [comment]
I can look into this.

**Comment by dganzi** [comment]
I believe this was completed elsewhere. If I can find the ticket again, I will post the number.

**Comment by summetj** [comment]
> I believe this was completed elsewhere. If I can find the ticket again, I will post the number.

If you confirm it is completed I'd love to close it.

**Comment by Patrick-Erichsen** [comment]
Closing as we have UI/UX work in flight to refactor this screen.
