### ISSUE TITLE
Choose health authority : Add trusted source button overlaps the "paste url" text box upon click

### ISSUE THREAD

**Issue by vedhakannan** [Path-Check/covid-safe-paths#674]
Choose health authority : Add trusted source button overlaps the "paste url" text box upon click

Issue type : UI/UX
Safe paths version : 1.0.0

## Version

- Type of phone: Android 
- OS Version: 9
- Model: Moto g 6 plus

## Steps to reproduce

1. Get onboarded.
2. Dashboard -> Choose health authority -> Add authority via URL 
3. Click on the text box, to paste the url

Issue : The "add trusted source " button overlaps the "paste your url" text box.

![addauthority](https://user-images.githubusercontent.com/63336927/80212184-a9101600-8654-11ea-8b21-46656827b46f.jpeg)

**Comment by diarmidmackenzie** [comment]
Same on Samsung Galaxy J6, but even worse - see screenshot.

![image](https://user-images.githubusercontent.com/16045703/80280158-9fdd8280-8702-11ea-9ad4-158acd55d586.png)


I also noticed when trying to press the disk icon, that the area for the button seems to span the entire width of the screen.

But I think we are re-working this whole UI anyway?

**Comment by aartiverma1** [comment]
In case no re-working, assign this to me.

**Comment by Niniya173** [comment]
I also find the same issue in iPhone 5s, app version 1.0.1 and OS version 11.2.6.
Also at first, only the option to enter an URL is coming other options are visible only when a URL is added

**Comment by kuzahaha** [comment]
Do you have any progress?I can help you with this issue if u need
