### ISSUE TITLE
In Haitian Creole, Android permisions requests are still in English

### ISSUE THREAD

**Issue by diarmidmackenzie** [Path-Check/covid-safe-paths#676]
## Version

v1.0.0
Android 9
Moto G7

## Steps to reproduce

Set app to Haitian Crelo language.
Get to the stage where the app asks for locaton permissions (during setup) or for media & files permissions (data export).
In each case, the permissions request is in English.

Note that my phone is set up with English as the language.  As far as I can see, Haitian Creole is not available as a language on Android.

However I note that other OS messages such as App Notifications are in Haitian Creole.

## Expected Behavior

I expected all text generated by the App to be in Haitian Creole.

I am not certain whether tha's a correct expectation - if the behaviour described is expected to Dev,i iI'd be happy to close as is.

## Upload any files to the Issue useful in helping us to investigate

Here;s the location example - I assume the two cases are equivalent.

![image](https://user-images.githubusercontent.com/16045703/80232137-b4634180-8654-11ea-979f-fb5905dd1e0a.png)

**Comment by efalkner** [comment]
This is reproducible on iOS also. /Users/lizfalkner/git/forks/covid-safe-paths/e2e/artifacts/✓ Onboarding test suite in ht-HT Onboarding visual appearance Navigates through the onboarding without visual regression/Location Permissions Dialog.png

**Comment by prasad79** [comment]
On Android these alerts are system managed. So the alerts will be the displayed in the System language the Android Phone is configured in.
This should be similar in case of iOS device.

**Comment by Patrick-Erichsen** [comment]
Closing as these strings have been updated.
