### ISSUE TITLE
Choose health authority: Minor UX issues

### ISSUE THREAD

**Issue by AdamLeonSmith** [Path-Check/covid-safe-paths#683]
## Version

- Type of phone: Android 
- Model: Pixel 2
- V1.0 released to app store

## Steps to reproduce
UX is confusing. A floppy disk is a weird 'confirm' button and there is no confirmation of acceptance (until you go back)

## Expected Behavior
Experience should be more intuitive

**Comment by dganzi** [comment]
Hey there, do you have a screenshot of this behavior?

**Comment by AdamLeonSmith** [comment]
![WhatsApp Image 2020-04-27 at 16 12 52](https://user-images.githubusercontent.com/48051844/80388622-04831380-88a2-11ea-9782-5df5320462b7.jpeg)
![WhatsApp Image 2020-04-27 at 16 12 44](https://user-images.githubusercontent.com/48051844/80388631-064cd700-88a2-11ea-99f4-283a8b187b3d.jpeg)

Screenshots attached

**Comment by vestial** [comment]
This looks similar to issue #457 .

**Comment by summetj** [comment]
There are a few issues mentioned in #457 that still need to be resolved as well. If you decide to work on this guy, also look at #457.

If it's just your first issue, you might want to pick one item (perhaps replace the floppy disk with a save button?) to address.

**Comment by pauladam316** [comment]
I'd like to try tackling the save button problem as a first issue. Can you assign it to me?

**Comment by summetj** [comment]
@pauladam316  - You'll want to check in with the UI/UX people on the #appdev channel with your suggestion for what to replace the floppy disk icon with to make sure it fits their overall plans.

**Comment by pauladam316** [comment]
@summetj is #appdev a slack channel? Would you be able to send me an invite to that? Thanks!

**Comment by summetj** [comment]
Yes, it is. If you have not already, fill out the volunteer intake form (as that is where you would normally get access to the slack, developer instructions, etc....)
https://docs.google.com/forms/d/e/1FAIpQLSdzqAxrlrxb_HqLh1KXnfPu1rse4aByS2krL1OYlN3qKChyqA/viewform

Here is a direct slack invite link:
https://join.slack.com/t/covidsafepaths/shared_invite/zt-don4bveq-T83ROZfvSthT03zXy5vFeg

**Comment by driedgrape** [comment]
Hi folks, thanks for your input on the health authority page! The uiux team already have a few updates / changes in the works for selecting a health authority to make the process more straightforward for users
