### ISSUE TITLE
when use location is turned off in settings safe paths does not behave correctly.

### ISSUE THREAD

**Issue by aitkeni** [Path-Check/covid-safe-paths#685]
## Version  built off v 1.0.0 (24) commit 2b95fd40ec5c421c361b8eb1419ace8743926619

Android Pixel 2 API 28

## Steps to reproduce
open app
background app , 
open settings and disable use location
go back to app. 

Issue 1 notice location tracking still green/ enabled
expected - red / disabled

Issue 2 
Click green icon to disable message is displayed.
click on that message , the message is displayed again
keep clicking

expected - click on message would not trigger same message again

**Comment by aitkeni** [comment]
Noticed that there was some commented out code in LocationService.js#L227, L315 When I uncommented these blocks the situation improved, specifically when app detects that use location is disabled it will present an Alert box allowing the user to open the settings and turn it on.  This then resolves issue 1.
When I went thru the history it seems this code was commented out during the merge to the new UI design.  What I am thinking is it was accidentally left commented out, or there may have been another reason which would need worked on. Can you confirm if you remember @kenpugsley .  If accidental, I can un-comment and get it all working again.
also can i ask what is the best way to refresh the settings page - when i change the state to active, sometimes need to force a refresh.

**Comment by ShreyaaSahu** [comment]
iPhone XR 
ios version 13.3 
App version 1.0.1

This issue is happening in ios App also .

**Comment by Niniya173** [comment]
Same issue is seen in
 iPhone 5S
ios version 11.2.6
App version 1.0.1

**Comment by aitkeni** [comment]
thanks for confirming guys!  I have some code which tries to fix this issue and reenables the feature to open the location settings so user can turn it on.  just ironing out some scenarios where it gets confused about its state.  will make a PR today hopefully.

**Comment by tstirrat** [comment]
Issue 1 fixed in #749 

Issue 2 tracked in #656
