### ISSUE TITLE
TESTING: Verify logging resumes on reboot

### ISSUE THREAD

**Issue by penrods** [Path-Check/covid-safe-paths#72]
Like the title says!  Please note in comments if you see it work under iPhone and under Android.

**Comment by andreanuzzo** [comment]
iOS: logging does not seem to resume when switching between foreground and background or between lock/unlock. App says "Stop recording location" but Log shows no further point every 5'. Exported data agree with save points from Log.

**Comment by Rikku-1** [comment]
I tested this in iOS, and logging resumed after turning the device off and back on.

**Comment by harshvitra** [comment]
- [ ]  Android - Test if logging works after Reboot

- [ ]  iOS - Test if logging works after Reboot

- [ ]  Android - Test if logging works after putting it to background

- [ ]  iOS - Test if logging works after putting it to background

If you test anyone of these please tick the tasks off @Rikku-1 @andreanuzzo

**Comment by tremblerz** [comment]
I highly encourage developers to check on different Android and iOS versions.
I have tested Android and iOS and they work when put on background. Android also works if we terminate the application. Whoever is checking iOS, you will see the location getting logged only when the device moves, if it is kept stationary it doesn't log but as soon as it changes we fill the location with redundant points.

**Comment by greggles** [comment]
I'm on Android 10 - after either hard power off or a restart the notification tray did not show that it was logging. When I opened the app it says it's logging.

**Comment by arvind-source** [comment]
I have tested the logging issue on below device and version it is working fine without making any changes in code:

Android: 
Android version - 9 on Samsung J7
Android version - 6 on Moto E5

iPhone: 
iPhone 7
iPhone8
iPhone 11

**Comment by summetj** [comment]
I plan to close this issue unless somebody else finds that it is not working on some other platform?

**Comment by tstirrat** [comment]
Fixed in #747 #788
