### ISSUE TITLE
"Private Kit" link in Latest News screen is displaying error - Android app v1.0.1

### ISSUE THREAD

**Issue by NaziyaNazir** [Path-Check/covid-safe-paths#733]
**Version**
Type of phone: Realme
OS Version: Android 9
Model: U1

**Steps to reproduce**
1. Open the App
2. Open Hamburger menu
3. Tap "Latest News" to navigate to SafePath News screen
4. Tap on link "Private Kit"

**Expected Behavior**
Private kit screen should be displayed

**Actual Behavior**
Error loading page is displayed

![Screenshot_2020-04-30-16-52-48-35_7279f4f2abc8c6febb8fd1ee45579eaa](https://user-images.githubusercontent.com/64524151/80704878-0dbeeb00-8b03-11ea-9b9d-6d8ed97018c2.png)

![Screenshot_2020-04-30-16-52-52-93_7279f4f2abc8c6febb8fd1ee45579eaa](https://user-images.githubusercontent.com/64524151/80704915-1c0d0700-8b03-11ea-8bd1-cc149e356726.png)

**Comment by summetj** [comment]
@skusunam is working on this one.

**Comment by skusunam** [comment]
@summetj I just tested this on Android 9 and it works fine. As you know "Latest News" page is displaying from this URL: [https://covidsafepaths.org/in-app-news](https://covidsafepaths.org/in-app-new)s and when there is a problem in displaying this page or any broken links on this page will cause this kind of defects. Currently, this page is partially broken and displaying "404 Not Found".

**Comment by summetj** [comment]
> @summetj I just tested this on Android 9 and it works fine. As you know "Latest News" page is displaying from this URL: [https://covidsafepaths.org/in-app-news](https://covidsafepaths.org/in-app-new)s and when there is a problem in displaying this page or any broken links on this page will cause this kind of defects. Currently, this page is partially broken and displaying "404 Not Found".


I have notified the website team to get this fixed.

**Comment by summetj** [comment]
We have fixed the 404 error by creating a 301 redirect on the website to move the old link to the correct link. (Also, the link will be updated in the next version of the app.)
