### ISSUE TITLE
Lock icon is slightly overlapping C in Commitment of About screen  - ios App v1.0.1

### ISSUE THREAD

**Issue by ShreyaaSahu** [Path-Check/covid-safe-paths#735]
## Version

- Type of phone: iPhone
- OS Version: ios 13.3
- Model: iPhone XR

## Steps to reproduce
1. open App
2. Tap on main menu option 
3. open "About "
4. Screen displays content 
5. on screen - Lock icon is slightly overlapping C in Commitment 

![IMG-4656](https://user-images.githubusercontent.com/64080646/80705484-25e33a00-8b04-11ea-9cce-bdebd87029fa.PNG)

## Expected Behavior
Lock icon is does not overlap C in Commitment

**Comment by NaziyaNazir** [comment]
Issue exists in Android 9 as well.

![Screenshot_2020-04-30-12-40-22-57_7279f4f2abc8c6febb8fd1ee45579eaa](https://user-images.githubusercontent.com/64524151/80706604-30063800-8b06-11ea-87c1-281456a15a35.png)

**Comment by NethravathiPuttraju** [comment]
Assign this to me . i will take a look into this .

**Comment by summetj** [comment]
> Assign this to me . i will take a look into this .
Great Thanks! Please coordinate with UI/UX people on Slack with your proposed solution to make sure it's not overlapping other work.

**Comment by driedgrape** [comment]
Here's the design reference file: [https://www.figma.com/file/aOz2hCg6agulId3mGCQIv8/Safe-Paths-Version-1.0.1?node-id=1243%3A3605]

For both titles on that screen:
line-height: 32px;
padding: 11px

**Comment by summetj** [comment]
> Here's the design reference file:
> https://www.figma.com/file/aOz2hCg6agulId3mGCQIv8/Safe-Paths-Version-1.0.1?node-id=1243%3A3605
> 
> For both titles on that screen:
> line-height: 32px;
> padding: 11px

FYI @driedgrape  - That file/link does not appear to have global view permissions
