### ISSUE TITLE
Back button navigation issue in Latest News Section - ios App v1.0.1 

### ISSUE THREAD

**Issue by ShreyaaSahu** [Path-Check/covid-safe-paths#736]
## Version

- Type of phone: iPhone
- OS Version: ios 13.3
- Model: iPhone XR

## Steps to reproduce
1. open App
2. Tap on main menu option 
3. open "Latest News "
4. Screen displays content  with few links 
5. Open any link   e.g. "Related Search"
6. "Related Search" screen open 
7. Tap on Back button 
8. User is taken to dashboard  - Main menu .

Steps are shown in screenshots -
Main menu  
![IMG-4657](https://user-images.githubusercontent.com/64080646/80705593-562ad880-8b04-11ea-95e6-679954dea705.PNG)

Latest News Screen
![IMG-4658](https://user-images.githubusercontent.com/64080646/80705600-5925c900-8b04-11ea-8f99-8bbd411d63d2.PNG)

"Related Search" screen
![IMG-4659](https://user-images.githubusercontent.com/64080646/80705604-5aef8c80-8b04-11ea-8ff5-65beafd6fa82.PNG)

User is taken to dashboard  - Main menu  
![IMG-4657](https://user-images.githubusercontent.com/64080646/80705593-562ad880-8b04-11ea-95e6-679954dea705.PNG)

## Expected Behavior

Back button will take user to previous screen -  Latest News Screen

**Comment by NaziyaNazir** [comment]
Issue exists in Android 9 as well.

**Comment by summetj** [comment]
This may not be a "bug". (We are not implementing a full featured web browser with a browsing history/breadcrumbs model.) I'll let @alpita-masurkar decide if this needs to be fixed or won't fix.  (I don't know if the specifications say exactly what this back behavior should be.....but I doubt it.)

**Comment by Patrick-Erichsen** [comment]
Closing as this is being addressed in a larger UI/UX refactor of the news screen.
