### ISSUE TITLE
Difficulty in scrolling of Content in Safe Paths News of Latest News screen- Android app v1.0.1

### ISSUE THREAD

**Issue by NaziyaNazir** [Path-Check/covid-safe-paths#737]
**Version**
Type of phone: Realme
OS Version: Android 9
Model: U1

**Steps to reproduce**
Open the App
Open Hamburger menu
Tap "Latest News" to navigate to SafePath News screen
Tap on Hamburger Menu against COVID SafePaths
Tap on FAQ and scroll through the contents

**Expected Behavior**
Content scrolling should be smooth and user friendly

Actual Behavior
Difficulty in scrolling of the content

**Comment by summetj** [comment]
Can you give more details about the difficulty? Is it lagging, skipping or not moving when you drag the content?

**Comment by NaziyaNazir** [comment]
It is not moving when I drag the content.

**Comment by Namit-Agrawal** [comment]
Hello! I would like to tackle this issue.

**Comment by summetj** [comment]
Thanks @Namit-Agrawal ! BTW- are you on our Slack? (I couldn't find you using your github name....) We have an #app_dev channel that would be good to get you connected with as well as a lot of documentation. If you fill out our volunteer onboarding form I'll send you all the details.
https://docs.google.com/forms/d/e/1FAIpQLSdzqAxrlrxb_HqLh1KXnfPu1rse4aByS2krL1OYlN3qKChyqA/viewform

**Comment by Namit-Agrawal** [comment]
Hi Jay,
I do have a slack account! Would love to get connected. I have filled out
the form below.

Best Regards,
Namit Agrawal

**Comment by summetj** [comment]
Hi @Namit-Agrawal I've added you to our slack space and the #app_dev channel.

**Comment by Patrick-Erichsen** [comment]
Closing as this is being addressed in a larger UI/UX refactoring.
