### ISSUE TITLE
Content of Latest News is not compatible - Android app v1.0.1

### ISSUE THREAD

**Issue by NaziyaNazir** [Path-Check/covid-safe-paths#738]
**Version**
Type of phone: Realme
OS Version: Android 9
Model: U1

**Steps to reproduce**
Open the App
Open Hamburger menu
Tap "Latest News" to navigate to SafePath News screen

**Expected Behavior**
Hamburger Menu against COVID SafePaths should be displayed within the window

**Actual Behavior**
Hamburger Menu against COVID SafePaths is cut

![Screenshot_2020-04-30-16-52-48-35_7279f4f2abc8c6febb8fd1ee45579eaa](https://user-images.githubusercontent.com/64524151/80706421-f2a1aa80-8b05-11ea-8445-f0aa2a3a14da.png)

**Comment by NaziyaNazir** [comment]
Retested and verified the fix. PFB the screenshot. 

Version
Type of phone: Realme
OS Version: Android 9
Model: U1

![Screenshot_2020-05-21-12-02-08-43_7279f4f2abc8c6febb8fd1ee45579eaa](https://user-images.githubusercontent.com/64524151/82530886-edaba600-9b5b-11ea-8abe-9dcd442e474b.png)

**Comment by sparks2209** [comment]
@summetj With the latest update from Angelique W. Lee (Web team), this issue is resolved, we can close this bug.
