### ISSUE TITLE
Previously added URL is auto-populated when trying to add authority via URL in "Choose Health Authority" screen - Android app v1.0.1

### ISSUE THREAD

**Issue by NaziyaNazir** [Path-Check/covid-safe-paths#740]
**Version**
Type of phone: Realme
OS Version: Android 9
Model: U1

**Steps to reproduce**
Open the App
Open Hamburger menu
Tap "Choose Health Authority"
Tap on "Add Trusted Source"
Tap on "Add authority via URL"
Add a URL say "egds.com" and save
Again, Tap on "Add Trusted Source" and Tap on "Add authority via URL"

**Expected Behavior**
Blank field to add URL should be displayed

**Actual Behavior**
Previously filled URL is auto-filled in the field

![Screenshot_2020-04-30-17-25-18-44_7279f4f2abc8c6febb8fd1ee45579eaa](https://user-images.githubusercontent.com/64524151/80708066-a5730800-8b08-11ea-9ae3-bc89e8aecafb.png)

**Comment by ShreyaaSahu** [comment]
**This is happening in IOS also :** 

"Google.com" already added -

![IMG-4665](https://user-images.githubusercontent.com/64080646/80708311-19adab80-8b09-11ea-8c3c-724836100ce0.PNG)

Tapped on "Add authority via URL" for new  , it displays the old one ( Editable )

![IMG-4666](https://user-images.githubusercontent.com/64080646/80708323-1c100580-8b09-11ea-9546-b2d2667f1c2f.PNG)

**Comment by summetj** [comment]
This might not be a bug. (If the user messed up the URL the first time, they might like the opportunity to edit it for a 2nd attempt.) I'll let @alpita-masurkar determine if this behavior is desired or not.

**Comment by Niniya173** [comment]
Same issue is seen in iPhone 5S version 11.2.6.

**Comment by Patrick-Erichsen** [comment]
Closing as this has been resolved.
