### ISSUE TITLE
"Choose Health Authority": misleading title?

### ISSUE THREAD

**Issue by PMKielstra** [Path-Check/covid-safe-paths#786]
I'm aware of #457 and #683 but this seems to me a bit like its own thing -- if you disagree, please feel free to merge this into either of them.

"Choose Health Authority" implies that you're supposed to pick exactly one from a list.  Although this is how most users would, I imagine, use the app, it's not the limit of functionality: we support having multiple health authorities at once, or at least the UI acts as if we do.  "Manage Health Authorities" might be better.

**Comment by PMKielstra** [comment]
I'm not the only one with this problem, by the way -- I got tipped off to this by someone from Implementation asking me to explain what the deal was with "Choose Health Authority" and whether he was supposed to choose just one or what.

**Comment by driedgrape** [comment]
Great input @PMKielstra. The UIUX is in the process of refining strings.

**Comment by Patrick-Erichsen** [comment]
Thanks for the feedback @PMKielstra ! We're going to close this issue as we've taken the feedback and are considering the new wording.
