### ISSUE TITLE
App no longer tracking locations in debug environment

### ISSUE THREAD

**Issue by troach-sf** [Path-Check/covid-safe-paths#797]
## Version 
- Debug build version: develop

## Affected Devices
- All

## Affected Languages
- All

## Steps to reproduce

A recent refactor moved from the home screen being LocationTracking.js to Main.js. The Main.js screen never calls LocationService.start() so location tracking will never begin.

Another issue is that the code to migrate to our encrypted db is missing on Main.js.

```
GetStoreData(LOCATION_DATA, false).then(locations => {
      if (Array.isArray(locations) && locations.length > 0) {
        NativeModules.SecureStorageManager.migrateExistingLocations(
          locations,
        ).then(() => {
          RemoveStoreData(LOCATION_DATA);
        });
      }
    });
```

## Expected Behavior

- When the app is installed and location tracking permissions have been granted, the app should start tracking locations.

**Comment by tstirrat** [comment]
That extra code should go in a service. not a view. it's important logic.

**Comment by troach-sf** [comment]
Sure, a service is definitely the best places. This code will hopefully be very temporary and can be moved entirely after majority of users have the encrypted build for 14 days

**Comment by tstirrat** [comment]
Sure, we can make it run once once per session and remove it after 15 days.
