### ISSUE TITLE
Change standard home indicator colors

### ISSUE THREAD

**Issue by shrix** [Path-Check/covid-safe-paths#832]
Currently we have two colors reflecting the infection status of a user on their app:
 - Green indicating that a user is fine, and has no infection detected by the system
 - Orange indicating that a user encountered someone w/ an infection, and probably could be infected too

An important aspect here is about the "conditions" under which these status change:
 - from green to orange
 - from orange to green

And if a user has the flexibility of ignoring the same, and reset an orange to green color.
We shall discuss them all under this story, and come up with a flow for the same.

**Comment by tstirrat** [comment]
We're tracking this in Jira: https://pathcheck.atlassian.net/browse/SAF-256
