### ISSUE TITLE
Feature request: self-reporting features

### ISSUE THREAD

**Issue by andreanuzzo** [Path-Check/covid-safe-paths#88]
From conversations with @ericlavigne on the MIT TR article: 

1. Due to the delay in testing, it might be better to implement self-reporting of previously visited locations (via pinpoints, not long/lat). The users would be able to populate at least some of the data not collected because they didn't install the app at the time, the app crashed on some days, etc.

2. We could implement the possibility of checking for negative results/ absence of symptoms, when distributing warnings to contacts. Might be useful to trace secondary contacts and refine predictions.

**Comment by E3V3A** [comment]
Great idea! 

3. Also because your phone may be out of battery when your at some place and/or you may have left your phone while taking the dog out or grocery shopping etc.

**Comment by Patrick-Erichsen** [comment]
Jira link - https://pathcheck.atlassian.net/browse/SAF-282
